1740024228904	Sync.LogManager	DEBUG	Flushing file log
1740024228918	Sync.LogManager	DEBUG	Log cleanup threshold time: 1739160228918
1740024228941	Sync.LogManager	DEBUG	Done deleting files.
1740026006710	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1740026006710	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1740026006711	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1740029572812	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1740029572812	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1740029572815	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1740029572817	Sync.Service	DEBUG	User-Agent: Zen/1.7.6b (Windows NT 10.0; Win64; x64) FxSync/1.137.0.20250207111303.desktop
1740029572817	Sync.Service	INFO	Starting sync at 2025-02-20 16:32:52 in browser session OTBtkeSxQVMG
1740029572817	Sync.Service	DEBUG	In sync: should login.
1740029572817	Sync.Service	INFO	User logged in successfully - verifying login.
1740029572817	Sync.SyncAuthManager	DEBUG	unlockAndVerifyAuthState has no FxA user
1740029572817	Sync.Status	DEBUG	Status.login: error.login.reason.no_username => error.login.reason.no_username
1740029572817	Sync.Status	DEBUG	Status.service: service.client_not_configured => service.client_not_configured
1740029572817	Sync.Service	DEBUG	Fetching unlocked auth state returned error.login.reason.no_username
1740029572817	Sync.ErrorHandler	ERROR	Sync encountered a login error
1740029572817	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1740029572817	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1740029572818	Sync.Service	DEBUG	Exception calling WrappedLock: Error: Login failed: error.login.reason.no_username(resource://services-sync/service.sys.mjs:1041:15) JS Stack trace: onNotify@service.sys.mjs:1041:15
1740029572818	Sync.Service	DEBUG	Not syncing: login returned false.
